spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.8/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform:
server:
   context-path: /sell

#logging:
#  level:
#    root: info
#  pattern:
#    console: "%d - %msg%n"
#  file: /var/log/tomcat/sell.log


#  path: /var/log/tomcat/